apiVersion: v1
kind: ServiceAccount
metadata:
  name: smart-staffing-sa
  namespace: default
  annotations:
    # Este é o Client ID da Managed Identity (User Assigned)
    azure.workload.identity/client-id: "${MANAGED_IDENTITY_CLIENT_ID}"